// API key// pk.eyJ1IjoiYm9uaG9tajI2IiwiYSI6ImNraTZtNnFrMDFsYnYyemxsaXhkNmRvZjcifQ.C9sYuiFXzSBHceGnvn8zug
const API_KEY = "pk.eyJ1IjoiYm9uaG9tajI2IiwiYSI6ImNraTZtNnFrMDFsYnYyemxsaXhkNmRvZjcifQ.C9sYuiFXzSBHceGnvn8zug"
